version: "3.9"

services:

  workspace:
    build:
      context: ./docker/workspace
      args:
        - USERNAME=${VS_USERNAME-vscode}
        - USER_UID=${USER_UID-1000}
        - USER_GID=${USER_GID-1000}
        - TIME_ZONE=${TIME_ZONE-UTC}
        - LOCALE=${LOCALE-C}
    tty: true
    volumes:
      - ../:/var/www
      - ./docker/workspace/config/php.ini:/usr/local/etc/php/conf.d/99-php.ini
    working_dir: /var/www
  
  nginx:
    build: ./docker/nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/config:/etc/nginx/conf.d
      - ../.docker/nginx/log:/var/log/nginx
      - ../:/var/www
    environment:
      - TZ=${TIME_ZONE-UTC}

  php:
    build:
      context: ./docker/php
      args:
        - USER_UID=${USER_UID-1000}
        - USER_GID=${USER_GID-1000}
    volumes:
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ../:/var/www
    working_dir: /var/www

  mariadb:
    image: mariadb:10.7.4
    ports:
      - "3308:3306"
    volumes:
      - testlink_dev_mariadb:/var/lib/mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_ALLOW_EMPTY_PASSWORD=no
      - TZ=${TIME_ZONE-UTC}

volumes:
  testlink_dev_mariadb:
    external: true